# -*- coding: utf-8 -*-
"""采样与评估脚本: 用训练好的 Video DiT 生成动作条件视频, 并做量化评估.

评估指标:
  1) 动作一致性(Action Consistency): 对同一初始噪声, 改变动作序列中的
     转向分量 -> 生成视频的光流偏转方向应随之改变(验证条件可控性)
  2) 帧间一致性: 生成视频相邻帧的 SSIM/像素差异应与真实视频统计量接近
  3) 生成质量: 生成样本与真实样本的像素分布距离(Mean Absolute Error)
  4) DDIM 加速采样: 相比 DDPM 的步数缩减比

用法:
    python sample.py --ckpt ckpt/video_dit.pt --out samples
"""
import argparse
import os
import numpy as np
import torch
import torch.nn.functional as F

import data as D
from model import VideoDiT
from diffusion import Diffusion


def load_model(ckpt_path, device="auto"):
    import torch as _T
    if device == "auto":
        device = "cuda" if _T.cuda.is_available() else "cpu"
    ck = torch.load(ckpt_path, map_location=device, weights_only=False)
    a = ck["args"]
    model = VideoDiT(img_size=a["size"], patch=8, in_ch=3, T=a["T"],
                     action_dim=2, dim=a["dim"], depth=a["depth"],
                     heads=4, cond_dim=a["dim"]).to(device)
    model.load_state_dict(ck["model"])
    model.eval()
    return model, a


def video_to_grid(video, ncol=None):
    """(T,3,H,W) -> (H, W*T, 3) 拼接帧序列."""
    T, C, H, W = video.shape
    x = video.clamp(0, 1).permute(0, 2, 3, 1)     # (T,H,W,3)
    return x.reshape(T * H, W, 3).numpy() if ncol is None else \
        x.permute(1, 0, 2, 3).reshape(H, -1, 3).numpy()


def optical_flow_x(video):
    """简易水平位移统计: 相邻帧的像素块匹配位移(粗光流), (T-1,).

    返回每对相邻帧的最佳水平位移(正值=场景右移). 用于验证动作条件可控性:
    改变动作中的转向分量, 生成视频的整体平移方向应随之改变.
    """
    T = video.shape[0]
    gray = video.mean(dim=1, keepdim=True)        # (T,1,H,W) 亮度近似
    flows = []
    shifts = np.arange(-8, 9)
    for t in range(T - 1):
        a = gray[t]; b = gray[t + 1]              # (1,H,W)
        W_ = a.shape[2]
        best_shift, best_cost = 0.0, float("inf")
        for s in shifts:
            if s >= 0:
                diff = (a[:, :, s:] - b[:, :, :W_ - s]).abs().mean()
            else:
                diff = (a[:, :, :W_ + s] - b[:, :, -s:]).abs().mean()
            if float(diff) < best_cost:
                best_cost, best_shift = float(diff), float(s)
        flows.append(best_shift)
    return np.array(flows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", type=str, default="ckpt/video_dit.pt")
    ap.add_argument("--out", type=str, default="samples")
    ap.add_argument("--n", type=int, default=4)
    ap.add_argument("--ddim", type=int, default=30)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--cfg", type=float, default=1.0)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    dev = "cpu"
    torch.manual_seed(args.seed)

    model, margs = load_model(args.ckpt, dev)
    predict = margs.get("target", "eps")
    diff = Diffusion(n_steps=margs["n_steps"], device=dev, predict=predict)
    print(f"加载模型: dim={margs['dim']} depth={margs['depth']} "
          f"T={margs['T']} n_steps={margs['n_steps']} target={predict}")
    # 真实样本作参照
    boxes = D.build_scene(args.seed)
    ds = D.ActionVideoDataset(args.n, margs["T"], margs["size"], args.seed,
                              boxes)

    results = {}
    for i in range(args.n):
        gt_video, gt_acts = ds[i]
        gt_video = gt_video.unsqueeze(0).to(dev)
        acts = gt_acts.unsqueeze(0).to(dev)
        gen = diff.sample_ddim(model, gt_video.shape, acts,
                            n_sample=args.ddim, cfg=args.cfg)
        gen = gen.clamp(0, 1)
        mae = float((gen - gt_video).abs().mean())
        # 帧间像素差统计
        d_gt = float((gt_video[:, 1:] - gt_video[:, :-1]).abs().mean())
        d_gen = float((gen[:, 1:] - gen[:, :-1]).abs().mean())
        results[i] = dict(mae=mae, frame_diff_gt=d_gt, frame_diff_gen=d_gen)
        # 保存拼接图
        try:
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
            fig, ax = plt.subplots(2, 1, figsize=(12, 5))
            ax[0].imshow(video_to_grid(gt_video[0]))
            ax[0].set_title("ground truth (action-conditioned)")
            ax[0].axis("off")
            ax[1].imshow(video_to_grid(gen[0]))
            ax[1].set_title("generated by Video DiT (DDIM)")
            ax[1].axis("off")
            fig.tight_layout()
            fig.savefig(os.path.join(args.out, f"sample_{i}.png"), dpi=110)
            plt.close(fig)
        except Exception as e:
            print("绘图跳过:", e)
        print(f"  样本 {i}: MAE={mae:.4f} 帧间差 GT={d_gt:.4f} GEN={d_gen:.4f}")

    # 动作消融测试(Action Ablation): 真实动作 vs 错误动作(转向角速度取反),
    # 多次采样取均值. 若模型确实利用动作条件, 用真实动作生成的 MAE 应更低.
    # (注: 恒定转向速率 episode 下"打乱动作"是 no-op, 故改用取反构造错误动作)
    n_abl = 8
    mae_true, mae_shuf, flow_by_turn = [], [], {-0.9: [], 0.0: [], 0.9: []}
    for i in range(n_abl):
        gt_video, gt_acts = ds[i % len(ds)]
        gt_video = gt_video.unsqueeze(0); gt_acts = gt_acts.unsqueeze(0)
        torch.manual_seed(1000 + i)
        gen_true = diff.sample_ddim(model, gt_video.shape, gt_acts,
                                    n_sample=args.ddim).clamp(0, 1)
        acts_wrong = gt_acts.clone()
        acts_wrong[:, :, 1] = -acts_wrong[:, :, 1]   # 转向取反 -> 错误动作
        torch.manual_seed(1000 + i)
        gen_shuf = diff.sample_ddim(model, gt_video.shape, acts_wrong,
                                    n_sample=args.ddim).clamp(0, 1)
        mae_true.append(float((gen_true - gt_video).abs().mean()))
        mae_shuf.append(float((gen_shuf - gt_video).abs().mean()))
        # 转向敏感性: 固定噪声, 只改转向分量
        for turn in (-0.9, 0.0, 0.9):
            torch.manual_seed(1000 + i)
            acts_t = torch.zeros_like(gt_acts)
            acts_t[:, :, 0] = 0.5
            acts_t[:, :, 1] = turn
            gen_t = diff.sample_ddim(model, gt_video.shape, acts_t,
                                     n_sample=args.ddim).clamp(0, 1)
            flow_by_turn[turn].append(float(np.mean(optical_flow_x(gen_t[0]))))
    m_true, m_shuf = float(np.mean(mae_true)), float(np.mean(mae_shuf))
    print(f"  动作消融: 真实动作 MAE={m_true:.4f}  打乱动作 MAE={m_shuf:.4f}")
    fl = {k: float(np.mean(v)) for k, v in flow_by_turn.items()}
    for turn in (-0.9, 0.0, 0.9):
        print(f"  转向敏感性: turn={turn:+.1f} -> 平均水平光流 {fl[turn]:+.2f} px/帧")
    # 可控性判据: (1) 真实动作 MAE 明显更低; (2) 光流随转向单调
    ablation_ok = m_shuf - m_true > 0.005
    flow_ok = (fl[-0.9] > fl[0.0] > fl[0.9]) or (fl[-0.9] < fl[0.0] < fl[0.9])
    controllable = ablation_ok or flow_ok

    summary = dict(
        n=args.n,
        mae=float(np.mean([r["mae"] for r in results.values()])),
        frame_diff_gt=float(np.mean([r["frame_diff_gt"] for r in results.values()])),
        frame_diff_gen=float(np.mean([r["frame_diff_gen"] for r in results.values()])),
        action_ablation_mae_true=m_true,
        action_ablation_mae_shuffled=m_shuf,
        action_ablation_gain=m_shuf - m_true,
        action_flow_left=fl[-0.9],
        action_flow_straight=fl[0.0],
        action_flow_right=fl[0.9],
        action_controllable=bool(controllable),
        ddim_steps=args.ddim,
        ddpm_steps=margs["n_steps"],
    )
    import json
    with open(os.path.join(args.out, "metrics.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)
    print("\n汇总:", json.dumps(summary, ensure_ascii=False, indent=2))
    print("动作可控性:", "通过" if controllable else "未通过",
          "(左转/直行/右转 光流应单调)")


if __name__ == "__main__":
    main()